# Detailed global status
SubsystemStatus global_status

# Detailed motion planning status
SubsystemStatus motion_planning

# Detailed localization status
SubsystemStatus localization

# Detailed perception status
SubsystemStatus perception

# Detailed status for hardware
SubsystemStatus hardware

# Detailed status for compute unit
SubsystemStatus compute

# Detailed status for network
SubsystemStatus network
