# Total computation time for kernel input filter
uint64 processing_time_us
string[] processing_time_detail

# Amplitude of the difference between desired and filtered input signal w.r.t the input
# domain
float64 input_modification

# Size of the regulation map
float64 regulation_map_size

# Maximum amplitude of the violation of the safety constraints
float64 safety_violation

# Amplitude of the input signal w.r.t the input domain
float64 input_amplitude
